language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-astiapp' ]; then cd .. && eval "mv $currentfolder generator-astiapp" && cd generator-astiapp; fi

